;---------------------------------------------------------------------------------------
; These definitions exist to completely bypass the code generated by the compiler. Be sure
; To also include any of these exported symbols in AssemblyFunctions.def so that they are
; exported in the dll.

extern CXWnd__CXWnd
extern CXWnd__dCXWnd
extern CSidlScreenWnd__CSidlScreenWnd1
extern CSidlScreenWnd__CSidlScreenWnd2
extern CSidlScreenWnd__dCSidlScreenWnd
extern CListWnd__CListWnd
extern CListWnd__dCListWnd
extern CInvSlotWnd__CInvSlotWnd
extern CMapViewWnd__CMapViewWnd
extern MapViewMap__MapViewMap
extern MapViewMap__dMapViewMap
extern CChatWindow__CChatWindow
;extern ItemClient__ItemClient
extern ItemClient__dItemClient
extern EQItemList__EQItemList

section .text

global ??0CXWnd@eqlib@@QEAA@PEAV01@IVCXRect@1@@Z
??0CXWnd@eqlib@@QEAA@PEAV01@IVCXRect@1@@Z:
	mov rax, [qword CXWnd__CXWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??1CXWnd@eqlib@@UEAA@XZ
??1CXWnd@eqlib@@UEAA@XZ:
	mov rax, [qword CXWnd__dCXWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CListWnd@eqlib@@QEAA@PEAVCXWnd@1@IAEBVCXRect@1@@Z
??0CListWnd@eqlib@@QEAA@PEAVCXWnd@1@IAEBVCXRect@1@@Z:
	mov rax, [qword CListWnd__CListWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??1CListWnd@eqlib@@UEAA@XZ
??1CListWnd@eqlib@@UEAA@XZ:
	mov rax, [qword CListWnd__dCListWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CInvSlotWnd@eqlib@@QEAA@PEAVCXWnd@1@IVCXRect@1@PEAVCTextureAnimation@1@AEBVItemGlobalIndex@1@HH@Z
??0CInvSlotWnd@eqlib@@QEAA@PEAVCXWnd@1@IVCXRect@1@PEAVCTextureAnimation@1@AEBVItemGlobalIndex@1@HH@Z:
	mov rax, [qword CInvSlotWnd__CInvSlotWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CMapViewWnd@eqlib@@QEAA@PEAVCXWnd@1@@Z
??0CMapViewWnd@eqlib@@QEAA@PEAVCXWnd@1@@Z:
	mov rax, [qword CMapViewWnd__CMapViewWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0MapViewMap@eqlib@@QEAA@XZ
??0MapViewMap@eqlib@@QEAA@XZ:
	mov rax, [qword MapViewMap__MapViewMap]
	jmp rax

;---------------------------------------------------------------------------------------

global ??1MapViewMap@eqlib@@UEAA@XZ
??1MapViewMap@eqlib@@UEAA@XZ:
	mov rax, [qword MapViewMap__dMapViewMap]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CChatWindow@eqlib@@QEAA@PEAVCXWnd@1@@Z
??0CChatWindow@eqlib@@QEAA@PEAVCXWnd@1@@Z:
	mov rax, [qword CChatWindow__CChatWindow]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@@Z
??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@@Z:
	mov rax, [qword CSidlScreenWnd__CSidlScreenWnd1]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@HHPEAD@Z
??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@HHPEAD@Z:
	mov rax, [qword CSidlScreenWnd__CSidlScreenWnd2]
	jmp rax

;---------------------------------------------------------------------------------------

global ??1CSidlScreenWnd@eqlib@@UEAA@XZ
??1CSidlScreenWnd@eqlib@@UEAA@XZ:
	mov rax, [qword CSidlScreenWnd__dCSidlScreenWnd]
	jmp rax

;---------------------------------------------------------------------------------------

;global ??0ItemClient@eqlib@@QEAA@XZ
;??0ItemClient@eqlib@@QEAA@XZ:
;	mov rax, [qword ItemClient__ItemClient]
;	jmp rax

;---------------------------------------------------------------------------------------

global ??1ItemClient@eqlib@@UEAA@XZ
??1ItemClient@eqlib@@UEAA@XZ:
	mov rax, [qword ItemClient__dItemClient]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0EQItemList@eqlib@@QEAA@XZ
??0EQItemList@eqlib@@QEAA@XZ:
	mov rax, [qword EQItemList__EQItemList]
	jmp rax
	
