;---------------------------------------------------------------------------------------
; These definitions exist to completely bypass the code generated by the compiler. Be sure
; To also include any of these exported symbols in AssemblyFunctions.def so that they are
; exported in the dll.

extern CInvSlotWnd__CInvSlotWnd
extern CMapViewWnd__CMapViewWnd
extern CChatWindow__CChatWindow
;extern ItemClient__ItemClient
extern ItemClient__dItemClient
extern EQItemList__EQItemList

section .text


;---------------------------------------------------------------------------------------

global ??0CInvSlotWnd@eqlib@@QEAA@PEAVCXWnd@1@IVCXRect@1@PEAVCTextureAnimation@1@AEBVItemGlobalIndex@1@HH@Z
export ??0CInvSlotWnd@eqlib@@QEAA@PEAVCXWnd@1@IVCXRect@1@PEAVCTextureAnimation@1@AEBVItemGlobalIndex@1@HH@Z
??0CInvSlotWnd@eqlib@@QEAA@PEAVCXWnd@1@IVCXRect@1@PEAVCTextureAnimation@1@AEBVItemGlobalIndex@1@HH@Z:
	mov rax, [qword CInvSlotWnd__CInvSlotWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0CMapViewWnd@eqlib@@QEAA@PEAVCXWnd@1@@Z
export ??0CMapViewWnd@eqlib@@QEAA@PEAVCXWnd@1@@Z
??0CMapViewWnd@eqlib@@QEAA@PEAVCXWnd@1@@Z:
	mov rax, [qword CMapViewWnd__CMapViewWnd]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0MapViewMap@eqlib@@QEAA@XZ
export ??0MapViewMap@eqlib@@QEAA@XZ
??0MapViewMap@eqlib@@QEAA@XZ:
	mov rax, rcx
	ret

;---------------------------------------------------------------------------------------

global ??1MapViewMap@eqlib@@UEAA@XZ
export ??1MapViewMap@eqlib@@UEAA@XZ
??1MapViewMap@eqlib@@UEAA@XZ:
	mov rax, rcx
	ret

;---------------------------------------------------------------------------------------

global ??0CChatWindow@eqlib@@QEAA@PEAVCXWnd@1@@Z
export ??0CChatWindow@eqlib@@QEAA@PEAVCXWnd@1@@Z
??0CChatWindow@eqlib@@QEAA@PEAVCXWnd@1@@Z:
	mov rax, [qword CChatWindow__CChatWindow]
	jmp rax


;---------------------------------------------------------------------------------------

global ??1ItemClient@eqlib@@UEAA@XZ
export ??1ItemClient@eqlib@@UEAA@XZ
??1ItemClient@eqlib@@UEAA@XZ:
	mov rax, [qword ItemClient__dItemClient]
	jmp rax

;---------------------------------------------------------------------------------------

global ??0EQItemList@eqlib@@QEAA@XZ
export ??0EQItemList@eqlib@@QEAA@XZ
??0EQItemList@eqlib@@QEAA@XZ:
	mov rax, [qword EQItemList__EQItemList]
	jmp rax
	


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CXWnd

; eqlib::CXWnd::VirtualFunctionTable * eqlib::CXWnd::sm_vftable
extern ?sm_vftable@CXWnd@eqlib@@2PEAUVirtualFunctionTable@12@EA

extern CXWnd__CXWnd
extern CXWnd__dCXWnd
extern CXWnd__GetScreenClipRect
extern CXWnd__GetScreenRect

; public: eqlib::CXWnd::CXWnd(class eqlib::CXWnd *, unsigned int, class eqlib::CXRect)
global ??0CXWnd@eqlib@@QEAA@PEAV01@IVCXRect@1@@Z
export ??0CXWnd@eqlib@@QEAA@PEAV01@IVCXRect@1@@Z
??0CXWnd@eqlib@@QEAA@PEAV01@IVCXRect@1@@Z:
	jmp [rel CXWnd__CXWnd]


; public: eqlib::CXWnd::~CXWnd()
global ??1CXWnd@eqlib@@UEAA@XZ
export ??1CXWnd@eqlib@@UEAA@XZ
??1CXWnd@eqlib@@UEAA@XZ:
	jmp [rel CXWnd__dCXWnd]


; public: class eqlib::CXRect eqlib::CXWnd::GetScreenClipRect(void)const
global ?GetScreenClipRect@CXWnd@eqlib@@QEBA?AVCXRect@2@XZ
export ?GetScreenClipRect@CXWnd@eqlib@@QEBA?AVCXRect@2@XZ
?GetScreenClipRect@CXWnd@eqlib@@QEBA?AVCXRect@2@XZ:
	jmp [rel CXWnd__GetScreenClipRect]


; public: class eqlib::CXRect eqlib::CXWnd::GetScreenRect(void)const
global ?GetScreenRect@CXWnd@eqlib@@QEBA?AVCXRect@2@XZ
export ?GetScreenRect@CXWnd@eqlib@@QEBA?AVCXRect@2@XZ
?GetScreenRect@CXWnd@eqlib@@QEBA?AVCXRect@2@XZ:
	jmp [rel CXWnd__GetScreenRect]


;---------------------------------------------------------------------------------------
; CXWnd Virtual Functions

%macro call_cxwnd_vtable 1
	mov  rax, [rel ?sm_vftable@CXWnd@eqlib@@2PEAUVirtualFunctionTable@12@EA]
	jmp  [rax+%1]

%endmacro

; public: virtual int eqlib::CXWnd::DrawNC(void)
global ?DrawNC@CXWnd@eqlib@@UEBAHXZ
export ?DrawNC@CXWnd@eqlib@@UEBAHXZ
?DrawNC@CXWnd@eqlib@@UEBAHXZ:
	call_cxwnd_vtable 0x10


; public: virtual int eqlib::CXWnd::DrawCursor(class eqlib::CXPoint const &, class eqlib::CXRect const &, bool &)
global ?DrawCursor@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@AEBVCXRect@2@AEA_N@Z
export ?DrawCursor@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@AEBVCXRect@2@AEA_N@Z
?DrawCursor@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@AEBVCXRect@2@AEA_N@Z:
	call_cxwnd_vtable 0x28


; public: virtual int eqlib::CXWnd::DrawBackground(void)const
global ?DrawBackground@CXWnd@eqlib@@UEBAHXZ
export ?DrawBackground@CXWnd@eqlib@@UEBAHXZ
?DrawBackground@CXWnd@eqlib@@UEBAHXZ:
	call_cxwnd_vtable 0x40


; public: virtual int eqlib::CXWnd::DrawTooltip(class eqlib::CXWnd const *)const
global ?DrawTooltip@CXWnd@eqlib@@UEBAHPEBV12@@Z
export ?DrawTooltip@CXWnd@eqlib@@UEBAHPEBV12@@Z
?DrawTooltip@CXWnd@eqlib@@UEBAHPEBV12@@Z:
	call_cxwnd_vtable 0x48


; public: virtual int eqlib::CXWnd::DrawTooltipAtPoint(class eqlib::CXPoint const &, class eqlib::CXStr const &)const
global ?DrawTooltipAtPoint@CXWnd@eqlib@@UEBAHAEBVCXPoint@2@AEBVCXStr@2@@Z
export ?DrawTooltipAtPoint@CXWnd@eqlib@@UEBAHAEBVCXPoint@2@AEBVCXStr@2@@Z
?DrawTooltipAtPoint@CXWnd@eqlib@@UEBAHAEBVCXPoint@2@AEBVCXStr@2@@Z:
	call_cxwnd_vtable 0x50


; public: virtual class eqlib::CXRect eqlib::CXWnd::GetMinimizedRect(void)const
global ?GetMinimizedRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
export ?GetMinimizedRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
?GetMinimizedRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ:
	call_cxwnd_vtable 0x58


; public: virtual int eqlib::CXWnd::DrawTitleBar(class eqlib::CXRect const &)const
global ?DrawTitleBar@CXWnd@eqlib@@UEBAHAEBVCXRect@2@@Z
export ?DrawTitleBar@CXWnd@eqlib@@UEBAHAEBVCXRect@2@@Z
?DrawTitleBar@CXWnd@eqlib@@UEBAHAEBVCXRect@2@@Z:
	call_cxwnd_vtable 0x60


; public: virtual struct HICON__ * eqlib::CXWnd::GetCursorToDisplay(void)const
global ?GetCursorToDisplay@CXWnd@eqlib@@UEBAPEAUHICON__@@XZ
export ?GetCursorToDisplay@CXWnd@eqlib@@UEBAPEAUHICON__@@XZ
?GetCursorToDisplay@CXWnd@eqlib@@UEBAPEAUHICON__@@XZ:
	call_cxwnd_vtable 0x68


; public: virtual int eqlib::CXWnd::HandleLButtonDown(class eqlib::CXPoint const &, unsigned int)
global ?HandleLButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleLButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleLButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0x70


; public: virtual int eqlib::CXWnd::HandleLButtonUp(class eqlib::CXPoint const &, unsigned int)
global ?HandleLButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleLButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleLButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0x78


; public: virtual int eqlib::CXWnd::HandleLButtonHeld(class eqlib::CXPoint const &, unsigned int)
global ?HandleLButtonHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleLButtonHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleLButtonHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0x80


; public: virtual int eqlib::CXWnd::HandleLButtonUpAfterHeld(class eqlib::CXPoint const &, unsigned int)
global ?HandleLButtonUpAfterHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleLButtonUpAfterHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleLButtonUpAfterHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0x88


; public: virtual int eqlib::CXWnd::HandleRButtonDown(class eqlib::CXPoint const &, unsigned int)
global ?HandleRButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleRButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleRButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0x90


; public: virtual int eqlib::CXWnd::HandleRButtonUp(class eqlib::CXPoint const &, unsigned int)
global ?HandleRButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleRButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleRButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0x98


; public: virtual int eqlib::CXWnd::HandleRButtonHeld(class eqlib::CXPoint const &, unsigned int)
global ?HandleRButtonHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleRButtonHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleRButtonHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0xa0


; public: virtual int eqlib::CXWnd::HandleRButtonUpAfterHeld(class eqlib::CXPoint const &, unsigned int)
global ?HandleRButtonUpAfterHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleRButtonUpAfterHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleRButtonUpAfterHeld@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0xa8


; public: virtual int eqlib::CXWnd::HandleWheelButtonDown(class eqlib::CXPoint const &, unsigned int)
global ?HandleWheelButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleWheelButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleWheelButtonDown@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0xb0


; public: virtual int eqlib::CXWnd::HandleWheelButtonUp(class eqlib::CXPoint const &, unsigned int)
global ?HandleWheelButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleWheelButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleWheelButtonUp@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0xb8


; public: virtual int eqlib::CXWnd::HandleMouseMove(class eqlib::CXPoint const &, unsigned int)
global ?HandleMouseMove@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleMouseMove@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleMouseMove@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_cxwnd_vtable 0xc0


; public: virtual int eqlib::CXWnd::HandleWheelMove(class eqlib::CXPoint const &, int, unsigned int)
global ?HandleWheelMove@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@HI@Z
export ?HandleWheelMove@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@HI@Z
?HandleWheelMove@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@HI@Z:
	call_cxwnd_vtable 0xc8


; public: virtual int eqlib::CXWnd::HandleKeyboardMsg(unsigned int, unsigned int, bool)
global ?HandleKeyboardMsg@CXWnd@eqlib@@UEAAHII_N@Z
export ?HandleKeyboardMsg@CXWnd@eqlib@@UEAAHII_N@Z
?HandleKeyboardMsg@CXWnd@eqlib@@UEAAHII_N@Z:
	call_cxwnd_vtable 0xd0


; public: virtual int eqlib::CXWnd::HandleMouseLeave(void)
global ?HandleMouseLeave@CXWnd@eqlib@@UEAAHXZ
export ?HandleMouseLeave@CXWnd@eqlib@@UEAAHXZ
?HandleMouseLeave@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0xd8


; public: virtual int eqlib::CXWnd::OnDragDrop(struct eqlib::SDragDropInfo *)
global ?OnDragDrop@CXWnd@eqlib@@UEAAHPEAUSDragDropInfo@2@@Z
export ?OnDragDrop@CXWnd@eqlib@@UEAAHPEAUSDragDropInfo@2@@Z
?OnDragDrop@CXWnd@eqlib@@UEAAHPEAUSDragDropInfo@2@@Z:
	call_cxwnd_vtable 0xe0


; public: virtual struct HICON__ * eqlib::CXWnd::GetDragDropCursor(struct eqlib::SDragDropInfo *)const
global ?GetDragDropCursor@CXWnd@eqlib@@UEBAPEAUHICON__@@PEAUSDragDropInfo@2@@Z
export ?GetDragDropCursor@CXWnd@eqlib@@UEBAPEAUHICON__@@PEAUSDragDropInfo@2@@Z
?GetDragDropCursor@CXWnd@eqlib@@UEBAPEAUHICON__@@PEAUSDragDropInfo@2@@Z:
	call_cxwnd_vtable 0xe8


; public: virtual bool eqlib::CXWnd::QueryDropOK(struct eqlib::SDragDropInfo *)const
global ?QueryDropOK@CXWnd@eqlib@@UEBA_NPEAUSDragDropInfo@2@@Z
export ?QueryDropOK@CXWnd@eqlib@@UEBA_NPEAUSDragDropInfo@2@@Z
?QueryDropOK@CXWnd@eqlib@@UEBA_NPEAUSDragDropInfo@2@@Z:
	call_cxwnd_vtable 0xf0


; public: virtual int eqlib::CXWnd::OnClickStick(class eqlib::CClickStickInfo *, unsigned int, bool)
global ?OnClickStick@CXWnd@eqlib@@UEAAHPEAVCClickStickInfo@2@I_N@Z
export ?OnClickStick@CXWnd@eqlib@@UEAAHPEAVCClickStickInfo@2@I_N@Z
?OnClickStick@CXWnd@eqlib@@UEAAHPEAVCClickStickInfo@2@I_N@Z:
	call_cxwnd_vtable 0xf8


; public: virtual struct HICON__ * eqlib::CXWnd::GetClickStickCursor(class eqlib::CClickStickInfo *)const
global ?GetClickStickCursor@CXWnd@eqlib@@UEBAPEAUHICON__@@PEAVCClickStickInfo@2@@Z
export ?GetClickStickCursor@CXWnd@eqlib@@UEBAPEAUHICON__@@PEAVCClickStickInfo@2@@Z
?GetClickStickCursor@CXWnd@eqlib@@UEBAPEAUHICON__@@PEAVCClickStickInfo@2@@Z:
	call_cxwnd_vtable 0x100


; public: virtual bool eqlib::CXWnd::QueryClickStickDropOK(class eqlib::CClickStickInfo *)const
global ?QueryClickStickDropOK@CXWnd@eqlib@@UEBA_NPEAVCClickStickInfo@2@@Z
export ?QueryClickStickDropOK@CXWnd@eqlib@@UEBA_NPEAVCClickStickInfo@2@@Z
?QueryClickStickDropOK@CXWnd@eqlib@@UEBA_NPEAVCClickStickInfo@2@@Z:
	call_cxwnd_vtable 0x108


; public: virtual int eqlib::CXWnd::WndNotification(class eqlib::CXWnd *, unsigned int, void *)
global ?WndNotification@CXWnd@eqlib@@UEAAHPEAV12@IPEAX@Z
export ?WndNotification@CXWnd@eqlib@@UEAAHPEAV12@IPEAX@Z
?WndNotification@CXWnd@eqlib@@UEAAHPEAV12@IPEAX@Z:
	call_cxwnd_vtable 0x110


; public: virtual void eqlib::CXWnd::OnWndNotification(void)
global ?OnWndNotification@CXWnd@eqlib@@UEAAXXZ
export ?OnWndNotification@CXWnd@eqlib@@UEAAXXZ
?OnWndNotification@CXWnd@eqlib@@UEAAXXZ:
	call_cxwnd_vtable 0x118


; public: virtual int eqlib::CXWnd::OnShow(void)
global ?OnShow@CXWnd@eqlib@@UEAAHXZ
export ?OnShow@CXWnd@eqlib@@UEAAHXZ
?OnShow@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x130


; public: virtual int eqlib::CXWnd::OnMove(class eqlib::CXRect const &)
global ?OnMove@CXWnd@eqlib@@UEAAHAEBVCXRect@2@@Z
export ?OnMove@CXWnd@eqlib@@UEAAHAEBVCXRect@2@@Z
?OnMove@CXWnd@eqlib@@UEAAHAEBVCXRect@2@@Z:
	call_cxwnd_vtable 0x138


; public: virtual int eqlib::CXWnd::OnResize(int, int)
global ?OnResize@CXWnd@eqlib@@UEAAHHH@Z
export ?OnResize@CXWnd@eqlib@@UEAAHHH@Z
?OnResize@CXWnd@eqlib@@UEAAHHH@Z:
	call_cxwnd_vtable 0x140


; public: virtual int eqlib::CXWnd::OnBeginMoveOrResize(void)
global ?OnBeginMoveOrResize@CXWnd@eqlib@@UEAAHXZ
export ?OnBeginMoveOrResize@CXWnd@eqlib@@UEAAHXZ
?OnBeginMoveOrResize@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x148


; public: virtual int eqlib::CXWnd::OnCompleteMoveOrResize(void)
global ?OnCompleteMoveOrResize@CXWnd@eqlib@@UEAAHXZ
export ?OnCompleteMoveOrResize@CXWnd@eqlib@@UEAAHXZ
?OnCompleteMoveOrResize@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x150


; public: virtual int eqlib::CXWnd::OnMinimizeBox(void)
global ?OnMinimizeBox@CXWnd@eqlib@@UEAAHXZ
export ?OnMinimizeBox@CXWnd@eqlib@@UEAAHXZ
?OnMinimizeBox@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x158


; public: virtual int eqlib::CXWnd::OnMaximizeBox(void)
global ?OnMaximizeBox@CXWnd@eqlib@@UEAAHXZ
export ?OnMaximizeBox@CXWnd@eqlib@@UEAAHXZ
?OnMaximizeBox@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x160


; public: virtual int eqlib::CXWnd::OnTileBox(void)
global ?OnTileBox@CXWnd@eqlib@@UEAAHXZ
export ?OnTileBox@CXWnd@eqlib@@UEAAHXZ
?OnTileBox@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x168


; public: virtual int eqlib::CXWnd::OnSetFocus(class eqlib::CXWnd *)
global ?OnSetFocus@CXWnd@eqlib@@UEAAHPEAV12@@Z
export ?OnSetFocus@CXWnd@eqlib@@UEAAHPEAV12@@Z
?OnSetFocus@CXWnd@eqlib@@UEAAHPEAV12@@Z:
	call_cxwnd_vtable 0x178


; public: virtual int eqlib::CXWnd::OnKillFocus(class eqlib::CXWnd *)
global ?OnKillFocus@CXWnd@eqlib@@UEAAHPEAV12@@Z
export ?OnKillFocus@CXWnd@eqlib@@UEAAHPEAV12@@Z
?OnKillFocus@CXWnd@eqlib@@UEAAHPEAV12@@Z:
	call_cxwnd_vtable 0x180


; public: virtual int eqlib::CXWnd::OnProcessFrame(void)
global ?OnProcessFrame@CXWnd@eqlib@@UEAAHXZ
export ?OnProcessFrame@CXWnd@eqlib@@UEAAHXZ
?OnProcessFrame@CXWnd@eqlib@@UEAAHXZ:
	call_cxwnd_vtable 0x188


; public: virtual int eqlib::CXWnd::OnVScroll(enum eqlib::EScrollCode, int)
global ?OnVScroll@CXWnd@eqlib@@UEAAHW4EScrollCode@2@H@Z
export ?OnVScroll@CXWnd@eqlib@@UEAAHW4EScrollCode@2@H@Z
?OnVScroll@CXWnd@eqlib@@UEAAHW4EScrollCode@2@H@Z:
	call_cxwnd_vtable 0x190


; public: virtual int eqlib::CXWnd::OnHScroll(enum eqlib::EScrollCode, int)
global ?OnHScroll@CXWnd@eqlib@@UEAAHW4EScrollCode@2@H@Z
export ?OnHScroll@CXWnd@eqlib@@UEAAHW4EScrollCode@2@H@Z
?OnHScroll@CXWnd@eqlib@@UEAAHW4EScrollCode@2@H@Z:
	call_cxwnd_vtable 0x198


; public: virtual int eqlib::CXWnd::Show(bool, bool, bool)
global ?Show@CXWnd@eqlib@@UEAAH_N00@Z
export ?Show@CXWnd@eqlib@@UEAAH_N00@Z
?Show@CXWnd@eqlib@@UEAAH_N00@Z:
	call_cxwnd_vtable 0x1b0


; public: virtual bool eqlib::CXWnd::AboutToShow(void)
global ?AboutToShow@CXWnd@eqlib@@UEAA_NXZ
export ?AboutToShow@CXWnd@eqlib@@UEAA_NXZ
?AboutToShow@CXWnd@eqlib@@UEAA_NXZ:
	call_cxwnd_vtable 0x1b8


; public: virtual bool eqlib::CXWnd::AboutToHide(void)
global ?AboutToHide@CXWnd@eqlib@@UEAA_NXZ
export ?AboutToHide@CXWnd@eqlib@@UEAA_NXZ
?AboutToHide@CXWnd@eqlib@@UEAA_NXZ:
	call_cxwnd_vtable 0x1c0


; public: virtual void eqlib::CXWnd::Unknown0x0EC(void)
global ?Unknown0x0EC@CXWnd@eqlib@@UEAAXXZ
export ?Unknown0x0EC@CXWnd@eqlib@@UEAAXXZ
?Unknown0x0EC@CXWnd@eqlib@@UEAAXXZ:
	call_cxwnd_vtable 0x1d8


; public: virtual int eqlib::CXWnd::HitTest(class eqlib::CXPoint const &, int *)const
global ?HitTest@CXWnd@eqlib@@UEBAHAEBVCXPoint@2@PEAH@Z
export ?HitTest@CXWnd@eqlib@@UEBAHAEBVCXPoint@2@PEAH@Z
?HitTest@CXWnd@eqlib@@UEBAHAEBVCXPoint@2@PEAH@Z:
	call_cxwnd_vtable 0x1e0


; public: virtual class eqlib::CXRect eqlib::CXWnd::GetHitTestRect(int)const
global ?GetHitTestRect@CXWnd@eqlib@@UEBA?AVCXRect@2@H@Z
export ?GetHitTestRect@CXWnd@eqlib@@UEBA?AVCXRect@2@H@Z
?GetHitTestRect@CXWnd@eqlib@@UEBA?AVCXRect@2@H@Z:
	call_cxwnd_vtable 0x1e8


; public: virtual class eqlib::CXRect eqlib::CXWnd::GetInnerRect(void)const
global ?GetInnerRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
export ?GetInnerRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
?GetInnerRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ:
	call_cxwnd_vtable 0x1f0


; public: virtual class eqlib::CXRect eqlib::CXWnd::GetClientRect(void)const
global ?GetClientRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
export ?GetClientRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
?GetClientRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ:
	call_cxwnd_vtable 0x1f8


; public: virtual class eqlib::CXRect eqlib::CXWnd::GetClientClipRect(void)const
global ?GetClientClipRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
export ?GetClientClipRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ
?GetClientClipRect@CXWnd@eqlib@@UEBA?AVCXRect@2@XZ:
	call_cxwnd_vtable 0x200


; public: virtual class eqlib::CXSize eqlib::CXWnd::GetMinSize(bool)const
global ?GetMinSize@CXWnd@eqlib@@UEBA?AVCXSize@2@_N@Z
export ?GetMinSize@CXWnd@eqlib@@UEBA?AVCXSize@2@_N@Z
?GetMinSize@CXWnd@eqlib@@UEBA?AVCXSize@2@_N@Z:
	call_cxwnd_vtable 0x208


; public: virtual class eqlib::CXSize eqlib::CXWnd::GetMaxSize(bool)const
global ?GetMaxSize@CXWnd@eqlib@@UEBA?AVCXSize@2@_N@Z
export ?GetMaxSize@CXWnd@eqlib@@UEBA?AVCXSize@2@_N@Z
?GetMaxSize@CXWnd@eqlib@@UEBA?AVCXSize@2@_N@Z:
	call_cxwnd_vtable 0x210


; public: virtual int eqlib::CXWnd::UpdateGeometry(class eqlib::CXRect const &, bool, bool, bool, bool)
global ?UpdateGeometry@CXWnd@eqlib@@UEAAHAEBVCXRect@2@_N111@Z
export ?UpdateGeometry@CXWnd@eqlib@@UEAAHAEBVCXRect@2@_N111@Z
?UpdateGeometry@CXWnd@eqlib@@UEAAHAEBVCXRect@2@_N111@Z:
	call_cxwnd_vtable 0x240


; public: virtual int eqlib::CXWnd::Move(class eqlib::CXPoint const &)
global ?Move@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@@Z
export ?Move@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@@Z
?Move@CXWnd@eqlib@@UEAAHAEBVCXPoint@2@@Z:
	call_cxwnd_vtable 0x248


; public: virtual class eqlib::CXWnd * eqlib::CXWnd::GetChildWndAt(class eqlib::CXPoint const &, bool, bool)const
global ?GetChildWndAt@CXWnd@eqlib@@UEBAPEAV12@AEBVCXPoint@2@_N1@Z
export ?GetChildWndAt@CXWnd@eqlib@@UEBAPEAV12@AEBVCXPoint@2@_N1@Z
?GetChildWndAt@CXWnd@eqlib@@UEBAPEAV12@AEBVCXPoint@2@_N1@Z:
	call_cxwnd_vtable 0x258


; public: virtual class eqlib::CScreenPieceTemplate * eqlib::CXWnd::GetSidlPiece(class eqlib::CXStr const &, bool)const
global ?GetSidlPiece@CXWnd@eqlib@@UEBAPEAVCScreenPieceTemplate@2@AEBVCXStr@2@_N@Z
export ?GetSidlPiece@CXWnd@eqlib@@UEBAPEAVCScreenPieceTemplate@2@AEBVCXStr@2@_N@Z
?GetSidlPiece@CXWnd@eqlib@@UEBAPEAVCScreenPieceTemplate@2@AEBVCXStr@2@_N@Z:
	call_cxwnd_vtable 0x260


; public: virtual int eqlib::CXWnd::SetVScrollPos(int)
global ?SetVScrollPos@CXWnd@eqlib@@UEAAHH@Z
export ?SetVScrollPos@CXWnd@eqlib@@UEAAHH@Z
?SetVScrollPos@CXWnd@eqlib@@UEAAHH@Z:
	call_cxwnd_vtable 0x270


; public: virtual int eqlib::CXWnd::SetHScrollPos(int)
global ?SetHScrollPos@CXWnd@eqlib@@UEAAHH@Z
export ?SetHScrollPos@CXWnd@eqlib@@UEAAHH@Z
?SetHScrollPos@CXWnd@eqlib@@UEAAHH@Z:
	call_cxwnd_vtable 0x278


; public: virtual int eqlib::CXWnd::AutoSetVScrollPos(class eqlib::CXRect)
global ?AutoSetVScrollPos@CXWnd@eqlib@@UEAAHVCXRect@2@@Z
export ?AutoSetVScrollPos@CXWnd@eqlib@@UEAAHVCXRect@2@@Z
?AutoSetVScrollPos@CXWnd@eqlib@@UEAAHVCXRect@2@@Z:
	call_cxwnd_vtable 0x280


; public: virtual int eqlib::CXWnd::AutoSetHScrollPos(class eqlib::CXRect)
global ?AutoSetHScrollPos@CXWnd@eqlib@@UEAAHVCXRect@2@@Z
export ?AutoSetHScrollPos@CXWnd@eqlib@@UEAAHVCXRect@2@@Z
?AutoSetHScrollPos@CXWnd@eqlib@@UEAAHVCXRect@2@@Z:
	call_cxwnd_vtable 0x288


; public: virtual void eqlib::CXWnd::SetAttributesFromSidl(class eqlib::CParamScreenPiece *)
global ?SetAttributesFromSidl@CXWnd@eqlib@@UEAAXPEAVCParamScreenPiece@2@@Z
export ?SetAttributesFromSidl@CXWnd@eqlib@@UEAAXPEAVCParamScreenPiece@2@@Z
?SetAttributesFromSidl@CXWnd@eqlib@@UEAAXPEAVCParamScreenPiece@2@@Z:
	call_cxwnd_vtable 0x290


; public: virtual void eqlib::CXWnd::UpdateLayout(bool)
global ?UpdateLayout@CXWnd@eqlib@@UEAAX_N@Z
export ?UpdateLayout@CXWnd@eqlib@@UEAAX_N@Z
?UpdateLayout@CXWnd@eqlib@@UEAAX_N@Z:
	call_cxwnd_vtable 0x2c8


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CSidlScreenWnd

; eqlib::CSidlScreenWnd::VirtualFunctionTable * eqlib::CSidlScreenWnd::sm_vftable
extern ?sm_vftable@CSidlScreenWnd@eqlib@@2PEAUVirtualFunctionTable@12@EA

extern CSidlScreenWnd__CSidlScreenWnd1
extern CSidlScreenWnd__CSidlScreenWnd2
extern CSidlScreenWnd__dCSidlScreenWnd


; public: eqlib::CSidlScreenWnd::CSidlScreenWnd(class eqlib::CXWnd *,class eqlib::CXStr const &)
global ??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@@Z
export ??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@@Z
??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@@Z:
	mov rax, [qword CSidlScreenWnd__CSidlScreenWnd1]
	jmp rax


; public: eqlib::CSidlScreenWnd::CSidlScreenWnd(class eqlib::CXWnd *,class eqlib::CXStr const &,int,int,char *)
global ??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@HHPEAD@Z
export ??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@HHPEAD@Z
??0CSidlScreenWnd@eqlib@@QEAA@PEAVCXWnd@1@AEBVCXStr@1@HHPEAD@Z:
	mov rax, [qword CSidlScreenWnd__CSidlScreenWnd2]
	jmp rax


; public: virtual eqlib::CSidlScreenWnd::~CSidlScreenWnd(void)
global ??1CSidlScreenWnd@eqlib@@UEAA@XZ
export ??1CSidlScreenWnd@eqlib@@UEAA@XZ
??1CSidlScreenWnd@eqlib@@UEAA@XZ:
	mov rax, [qword CSidlScreenWnd__dCSidlScreenWnd]
	jmp rax


;---------------------------------------------------------------------------------------
; CSidlScreenWnd Virtual Functions

%macro call_csidlscreenwnd_vtable 1
	mov  rax, [rel ?sm_vftable@CSidlScreenWnd@eqlib@@2PEAUVirtualFunctionTable@12@EA]
	jmp  [rax+%1]

%endmacro


; public: virtual int eqlib::CSidlScreenWnd::OnResize(int, int)
global ?OnResize@CSidlScreenWnd@eqlib@@UEAAHHH@Z
export ?OnResize@CSidlScreenWnd@eqlib@@UEAAHHH@Z
?OnResize@CSidlScreenWnd@eqlib@@UEAAHHH@Z:
	call_csidlscreenwnd_vtable 0x140

; public: virtual int eqlib::CSidlScreenWnd::DrawBackground(void)const
global ?DrawBackground@CSidlScreenWnd@eqlib@@UEBAHXZ
export ?DrawBackground@CSidlScreenWnd@eqlib@@UEBAHXZ
?DrawBackground@CSidlScreenWnd@eqlib@@UEBAHXZ:
	call_csidlscreenwnd_vtable 0x40


; public: virtual int eqlib::CSidlScreenWnd::WndNotification(class eqlib::CXWnd *, unsigned int, void *)
global ?WndNotification@CSidlScreenWnd@eqlib@@UEAAHPEAVCXWnd@2@IPEAX@Z
export ?WndNotification@CSidlScreenWnd@eqlib@@UEAAHPEAVCXWnd@2@IPEAX@Z
?WndNotification@CSidlScreenWnd@eqlib@@UEAAHPEAVCXWnd@2@IPEAX@Z:
	call_csidlscreenwnd_vtable 0x110


; public: virtual int eqlib::CSidlScreenWnd::HandleRButtonDown(class eqlib::CXPoint const &, unsigned int)
global ?HandleRButtonDown@CSidlScreenWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
export ?HandleRButtonDown@CSidlScreenWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z
?HandleRButtonDown@CSidlScreenWnd@eqlib@@UEAAHAEBVCXPoint@2@I@Z:
	call_csidlscreenwnd_vtable 0x90


; public: virtual int eqlib::CSidlScreenWnd::OnShow(void)
global ?OnShow@CSidlScreenWnd@eqlib@@UEAAHXZ
export ?OnShow@CSidlScreenWnd@eqlib@@UEAAHXZ
?OnShow@CSidlScreenWnd@eqlib@@UEAAHXZ:
	call_csidlscreenwnd_vtable 0x130


; public: virtual class eqlib::CScreenPieceTemplate * eqlib::CSidlScreenWnd::GetSidlPiece(class eqlib::CXStr const &, bool)const
global ?GetSidlPiece@CSidlScreenWnd@eqlib@@UEBAPEAVCScreenPieceTemplate@2@AEBVCXStr@2@_N@Z
export ?GetSidlPiece@CSidlScreenWnd@eqlib@@UEBAPEAVCScreenPieceTemplate@2@AEBVCXStr@2@_N@Z
?GetSidlPiece@CSidlScreenWnd@eqlib@@UEBAPEAVCScreenPieceTemplate@2@AEBVCXStr@2@_N@Z:
	call_csidlscreenwnd_vtable 0x260


; public: virtual class eqlib::CXStr const * eqlib::CSidlScreenWnd::GetWindowName(void)const
global ?GetWindowName@CSidlScreenWnd@eqlib@@UEBAPEBVCXStr@2@XZ
export ?GetWindowName@CSidlScreenWnd@eqlib@@UEBAPEBVCXStr@2@XZ
?GetWindowName@CSidlScreenWnd@eqlib@@UEBAPEBVCXStr@2@XZ:
	call_csidlscreenwnd_vtable 0x268


; public: virtual bool eqlib::CSidlScreenWnd::HasActivatedFirstTimeAlert(void)const
global ?HasActivatedFirstTimeAlert@CSidlScreenWnd@eqlib@@UEBA_NXZ
export ?HasActivatedFirstTimeAlert@CSidlScreenWnd@eqlib@@UEBA_NXZ
?HasActivatedFirstTimeAlert@CSidlScreenWnd@eqlib@@UEBA_NXZ:
	call_csidlscreenwnd_vtable 0x2a0


; public: virtual void eqlib::CSidlScreenWnd::SetHasActivatedFirstTimeAlert(bool)
global ?SetHasActivatedFirstTimeAlert@CSidlScreenWnd@eqlib@@UEAAX_N@Z
export ?SetHasActivatedFirstTimeAlert@CSidlScreenWnd@eqlib@@UEAAX_N@Z
?SetHasActivatedFirstTimeAlert@CSidlScreenWnd@eqlib@@UEAAX_N@Z:
	call_csidlscreenwnd_vtable 0x2a8


; public: virtual int eqlib::CSidlScreenWnd::OnZone(void)
global ?OnZone@CSidlScreenWnd@eqlib@@UEAAHXZ
export ?OnZone@CSidlScreenWnd@eqlib@@UEAAHXZ
?OnZone@CSidlScreenWnd@eqlib@@UEAAHXZ:
	call_csidlscreenwnd_vtable 0x2d0


; public: virtual int eqlib::CSidlScreenWnd::OnPreZone(void)
global ?OnPreZone@CSidlScreenWnd@eqlib@@UEAAHXZ
export ?OnPreZone@CSidlScreenWnd@eqlib@@UEAAHXZ
?OnPreZone@CSidlScreenWnd@eqlib@@UEAAHXZ:
	call_csidlscreenwnd_vtable 0x2d8


; public: virtual void eqlib::CSidlScreenWnd::LoadIniInfo(void)
global ?LoadIniInfo@CSidlScreenWnd@eqlib@@UEAAXXZ
export ?LoadIniInfo@CSidlScreenWnd@eqlib@@UEAAXXZ
?LoadIniInfo@CSidlScreenWnd@eqlib@@UEAAXXZ:
	call_csidlscreenwnd_vtable 0x2e0


; public: virtual void eqlib::CSidlScreenWnd::StoreIniInfo(void)
global ?StoreIniInfo@CSidlScreenWnd@eqlib@@UEAAXXZ
export ?StoreIniInfo@CSidlScreenWnd@eqlib@@UEAAXXZ
?StoreIniInfo@CSidlScreenWnd@eqlib@@UEAAXXZ:
	call_csidlscreenwnd_vtable 0x2e8


; public: virtual class eqlib::CSidlScreenWnd * eqlib::CSidlScreenWnd::AsSidlScreenWnd(void)
global ?AsSidlScreenWnd@CSidlScreenWnd@eqlib@@UEAAPEAV12@XZ
export ?AsSidlScreenWnd@CSidlScreenWnd@eqlib@@UEAAPEAV12@XZ
?AsSidlScreenWnd@CSidlScreenWnd@eqlib@@UEAAPEAV12@XZ:
	call_csidlscreenwnd_vtable 0x2f0


; public: virtual bool eqlib::CSidlScreenWnd::GetScreenWndType(void)
global ?GetScreenWndType@CSidlScreenWnd@eqlib@@UEAA_NXZ
export ?GetScreenWndType@CSidlScreenWnd@eqlib@@UEAA_NXZ
?GetScreenWndType@CSidlScreenWnd@eqlib@@UEAA_NXZ:
	call_csidlscreenwnd_vtable 0x2f8


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CButtonWnd


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CChatWindow

extern CChatWindow__AddHistory


; void eqlib::CChatWindow::AddHistory(class eqlib::CXStr) proc near
global ?AddHistory@CChatWindow@eqlib@@QEAAXVCXStr@2@@Z
export ?AddHistory@CChatWindow@eqlib@@QEAAXVCXStr@2@@Z
?AddHistory@CChatWindow@eqlib@@QEAAXVCXStr@2@@Z:
	jmp [rel CChatWindow__AddHistory]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CComboWnd

extern CComboWnd__GetListRect


; public: class eqlib::CXRect eqlib::CComboWnd::GetListRect(bool)const
global ?GetListRect@CComboWnd@eqlib@@QEBA?AVCXRect@2@_N@Z
export ?GetListRect@CComboWnd@eqlib@@QEBA?AVCXRect@2@_N@Z
?GetListRect@CComboWnd@eqlib@@QEBA?AVCXRect@2@_N@Z:
	jmp [rel CComboWnd__GetListRect]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CEditWnd

extern CEditWnd__GetCharIndexPt
extern CEditWnd__GetSTMLSafeText
extern CEditWnd__ReplaceSelection


; public: class eqlib::CXPoint eqlib::CEditWnd::GetCharIndexPt(int)const
global ?GetCharIndexPt@CEditWnd@eqlib@@QEBA?AVCXPoint@2@H@Z
export ?GetCharIndexPt@CEditWnd@eqlib@@QEBA?AVCXPoint@2@H@Z
?GetCharIndexPt@CEditWnd@eqlib@@QEBA?AVCXPoint@2@H@Z:
	jmp [rel CEditWnd__GetCharIndexPt]


; public: class eqlib::CXStr eqlib::CEditWnd::GetSTMLSafeText(void)
global ?GetSTMLSafeText@CEditWnd@eqlib@@QEAA?AVCXStr@2@XZ_0
export ?GetSTMLSafeText@CEditWnd@eqlib@@QEAA?AVCXStr@2@XZ_0
?GetSTMLSafeText@CEditWnd@eqlib@@QEAA?AVCXStr@2@XZ_0:
	jmp [rel CEditWnd__GetSTMLSafeText]


; public: bool eqlib::CEditWnd::ReplaceSelection(class eqlib::CXStr, bool)
global ?ReplaceSelection@CEditWnd@eqlib@@QEAA_NVCXStr@2@_N@Z
export ?ReplaceSelection@CEditWnd@eqlib@@QEAA_NVCXStr@2@_N@Z
?ReplaceSelection@CEditWnd@eqlib@@QEAA_NVCXStr@2@_N@Z:
	jmp [rel CEditWnd__ReplaceSelection]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CInvSlot

extern CInvSlot__GetItemBase

; public: class eqlib::VePointer<class eqlib::ItemClient> eqlib::CInvSlot::GetItem(void)
global ?GetItem@CInvSlot@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@XZ
export ?GetItem@CInvSlot@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@XZ
?GetItem@CInvSlot@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@XZ:
	jmp [rel CInvSlot__GetItemBase]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CLargeDialogWnd

extern CLargeDialogWnd__Open


; void eqlib::CLargeDialogWnd::Open(bool, class eqlib::CXStr, unsigned long, class eqlib::CXStr, bool, class eqlib::CXStr, class eqlib::CXStr) proc near
global ?Open@CLargeDialogWnd@eqlib@@QEAAX_NVCXStr@2@K1011@Z
export ?Open@CLargeDialogWnd@eqlib@@QEAAX_NVCXStr@2@K1011@Z
?Open@CLargeDialogWnd@eqlib@@QEAAX_NVCXStr@2@K1011@Z:
	jmp [rel CLargeDialogWnd__Open]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CListWnd

; eqlib::CListWnd::VirtualFunctionTable * eqlib::CListWnd::sm_vftable
extern ?sm_vftable@CListWnd@eqlib@@2PEAUVirtualFunctionTable@12@EA

extern CListWnd__CListWnd
extern CListWnd__dCListWnd
extern CListWnd__AddColumn1
extern CListWnd__GetItemRect
extern CListWnd__GetItemText
extern CListWnd__GetSeparatorRect


; public: eqlib::CListWnd::CListWnd(class eqlib::CXWnd *,unsigned int,class eqlib::CXRect const &)
global ??0CListWnd@eqlib@@QEAA@PEAVCXWnd@1@IAEBVCXRect@1@@Z
export ??0CListWnd@eqlib@@QEAA@PEAVCXWnd@1@IAEBVCXRect@1@@Z
??0CListWnd@eqlib@@QEAA@PEAVCXWnd@1@IAEBVCXRect@1@@Z:
	jmp [rel CListWnd__CListWnd]


; public: virtual eqlib::CListWnd::~CListWnd(void)
global ??1CListWnd@eqlib@@UEAA@XZ
export ??1CListWnd@eqlib@@UEAA@XZ
??1CListWnd@eqlib@@UEAA@XZ:
	jmp [rel CListWnd__dCListWnd]


; public: class eqlib::CXStr eqlib::CListWnd::GetItemText(int, int)const
global ?GetItemText@CListWnd@eqlib@@QEBA?AVCXStr@2@HH@Z
export ?GetItemText@CListWnd@eqlib@@QEBA?AVCXStr@2@HH@Z
?GetItemText@CListWnd@eqlib@@QEBA?AVCXStr@2@HH@Z:
	jmp [rel CListWnd__GetItemText]


; int eqlib::CListWnd::AddColumn(class eqlib::CXStr const &, class eqlib::CTextureAnimation *, int, unsigned int, class eqlib::CXStr, unsigned int, class eqlib::CTextureAnimation *, class eqlib::CTextureAnimation *, bool, class eqlib::CXSize, class eqlib::CXPoint) proc near
global ?AddColumn@CListWnd@eqlib@@QEAAHAEBVCXStr@2@PEAVCTextureAnimation@2@HIV32@I11_NVCXSize@2@VCXPoint@2@@Z
export ?AddColumn@CListWnd@eqlib@@QEAAHAEBVCXStr@2@PEAVCTextureAnimation@2@HIV32@I11_NVCXSize@2@VCXPoint@2@@Z
?AddColumn@CListWnd@eqlib@@QEAAHAEBVCXStr@2@PEAVCTextureAnimation@2@HIV32@I11_NVCXSize@2@VCXPoint@2@@Z:
	jmp [rel CListWnd__AddColumn1]


; public: class eqlib::CXRect eqlib::CListWnd::GetItemRect(int, int)const
global ?GetItemRect@CListWnd@eqlib@@QEBA?AVCXRect@2@HH@Z
export ?GetItemRect@CListWnd@eqlib@@QEBA?AVCXRect@2@HH@Z
?GetItemRect@CListWnd@eqlib@@QEBA?AVCXRect@2@HH@Z:
	jmp [rel CListWnd__GetItemRect]


; public: class eqlib::CXRect eqlib::CListWnd::GetSeparatorRect(int)const
global ?GetSeparatorRect@CListWnd@eqlib@@QEBA?AVCXRect@2@H@Z
export ?GetSeparatorRect@CListWnd@eqlib@@QEBA?AVCXRect@2@H@Z
?GetSeparatorRect@CListWnd@eqlib@@QEBA?AVCXRect@2@H@Z:
	jmp [rel CListWnd__GetSeparatorRect]


;---------------------------------------------------------------------------------------
; CListWnd Virtual Functions

%macro call_clistwnd_vtable 1
	mov  rax, [rel ?sm_vftable@CListWnd@eqlib@@2PEAUVirtualFunctionTable@12@EA]
	jmp  [rax+%1]

%endmacro


; public: virtual class eqlib::CXRect eqlib::CListWnd::GetHitTestRect(int)const
global ?GetHitTestRect@CListWnd@eqlib@@UEBA?AVCXRect@2@H@Z
export ?GetHitTestRect@CListWnd@eqlib@@UEBA?AVCXRect@2@H@Z
?GetHitTestRect@CListWnd@eqlib@@UEBA?AVCXRect@2@H@Z:
	call_clistwnd_vtable 0x1e8


; public: virtual class eqlib::CXRect eqlib::CListWnd::GetClientClipRect(void)const
global ?GetClientClipRect@CListWnd@eqlib@@UEBA?AVCXRect@2@XZ
export ?GetClientClipRect@CListWnd@eqlib@@UEBA?AVCXRect@2@XZ
?GetClientClipRect@CListWnd@eqlib@@UEBA?AVCXRect@2@XZ:
	call_clistwnd_vtable 0x200


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CStmlWnd

extern CStmlWnd__AppendSTML
extern CStmlWnd__GetVisibleText
extern CStmlWnd__MakeStmlColorTag
extern CStmlWnd__MakeWndNotificationTag
extern CStmlWnd__SetSTMLText


; class eqlib::CXSize eqlib::CStmlWnd::AppendSTML(class eqlib::CXStr) proc near
global ?AppendSTML@CStmlWnd@eqlib@@QEAA?AVCXSize@2@VCXStr@2@@Z
export ?AppendSTML@CStmlWnd@eqlib@@QEAA?AVCXSize@2@VCXStr@2@@Z
?AppendSTML@CStmlWnd@eqlib@@QEAA?AVCXSize@2@VCXStr@2@@Z:
	jmp [rel CStmlWnd__AppendSTML]


; class eqlib::CXStr eqlib::CStmlWnd::GetVisibleText(class eqlib::CXStr, class eqlib::CXRect const &)const proc near
global ?GetVisibleText@CStmlWnd@eqlib@@QEBA?AVCXStr@2@V32@AEBVCXRect@2@@Z
export ?GetVisibleText@CStmlWnd@eqlib@@QEBA?AVCXStr@2@V32@AEBVCXRect@2@@Z
?GetVisibleText@CStmlWnd@eqlib@@QEBA?AVCXStr@2@V32@AEBVCXRect@2@@Z:
	jmp [rel CStmlWnd__GetVisibleText]


; public: static class eqlib::CXStr eqlib::CStmlWnd::MakeStmlColorTag(unsigned long)
global ?MakeStmlColorTag@CStmlWnd@eqlib@@SA?AVCXStr@2@K@Z
export ?MakeStmlColorTag@CStmlWnd@eqlib@@SA?AVCXStr@2@K@Z
?MakeStmlColorTag@CStmlWnd@eqlib@@SA?AVCXStr@2@K@Z:
	jmp [rel CStmlWnd__MakeStmlColorTag]


; public: static class eqlib::CXStr eqlib::CStmlWnd::MakeWndNotificationTag(unsigned int, class eqlib::CXStr const &, class eqlib::CXStr const &)
global ?MakeWndNotificationTag@CStmlWnd@eqlib@@SA?AVCXStr@2@IAEBV32@0@Z
export ?MakeWndNotificationTag@CStmlWnd@eqlib@@SA?AVCXStr@2@IAEBV32@0@Z
?MakeWndNotificationTag@CStmlWnd@eqlib@@SA?AVCXStr@2@IAEBV32@0@Z:
	jmp [rel CStmlWnd__MakeWndNotificationTag]


; void eqlib::CStmlWnd::SetSTMLText(class eqlib::CXStr, bool, struct eqlib::SLinkInfo *) proc near
global ?SetSTMLText@CStmlWnd@eqlib@@QEAAXVCXStr@2@_NPEAUSLinkInfo@2@@Z
export ?SetSTMLText@CStmlWnd@eqlib@@QEAAXVCXStr@2@_NPEAUSLinkInfo@2@@Z
?SetSTMLText@CStmlWnd@eqlib@@QEAAXVCXStr@2@_NPEAUSLinkInfo@2@@Z:
	jmp [rel CStmlWnd__SetSTMLText]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CTabWnd

extern CTabWnd__GetTabRect


; public: class eqlib::CXRect eqlib::CTabWnd::GetTabRect(int)const
global ?GetTabRect@CTabWnd@eqlib@@QEBA?AVCXRect@2@H@Z
export ?GetTabRect@CTabWnd@eqlib@@QEBA?AVCXRect@2@H@Z
?GetTabRect@CTabWnd@eqlib@@QEBA?AVCXRect@2@H@Z:
	jmp [rel CTabWnd__GetTabRect]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; CharacterBase

extern CharacterBase__GetItemByGlobalIndex
extern CharacterBase__GetItemByGlobalIndex1

; class eqlib::VePointer<class eqlib::ItemClient> eqlib::CharacterBase::GetItemByGlobalIndex(class eqlib::ItemGlobalIndex const &)const proc near
global ?GetItemByGlobalIndex@CharacterBase@eqlib@@QEBA?AV?$VePointer@VItemClient@eqlib@@@2@AEBVItemGlobalIndex@2@@Z
export ?GetItemByGlobalIndex@CharacterBase@eqlib@@QEBA?AV?$VePointer@VItemClient@eqlib@@@2@AEBVItemGlobalIndex@2@@Z
?GetItemByGlobalIndex@CharacterBase@eqlib@@QEBA?AV?$VePointer@VItemClient@eqlib@@@2@AEBVItemGlobalIndex@2@@Z:
	jmp [rel CharacterBase__GetItemByGlobalIndex]



; class eqlib::VePointer<class eqlib::ItemClient> eqlib::CharacterBase::GetItemByGlobalIndex(class eqlib::ItemGlobalIndex const &, enum eqlib::ItemContainer::CheckDepthOptions)const proc near
global ?GetItemByGlobalIndex@CharacterBase@eqlib@@QEBA?AV?$VePointer@VItemClient@eqlib@@@2@AEBVItemGlobalIndex@2@W4CheckDepthOptions@ItemContainer@2@@Z
export ?GetItemByGlobalIndex@CharacterBase@eqlib@@QEBA?AV?$VePointer@VItemClient@eqlib@@@2@AEBVItemGlobalIndex@2@W4CheckDepthOptions@ItemContainer@2@@Z
?GetItemByGlobalIndex@CharacterBase@eqlib@@QEBA?AV?$VePointer@VItemClient@eqlib@@@2@AEBVItemGlobalIndex@2@W4CheckDepthOptions@ItemContainer@2@@Z:
	jmp [rel CharacterBase__GetItemByGlobalIndex1]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; ItemBase

extern ItemClient__CreateItemClient


; public: class eqlib::VePointer<class eqlib::ItemClient> eqlib::ItemBase::CreateItemClient(class eqlib::CUnSerializeBuffer &)
global ?CreateItemClient@ItemBase@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@AEAVCUnSerializeBuffer@2@@Z
export ?CreateItemClient@ItemBase@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@AEAVCUnSerializeBuffer@2@@Z
?CreateItemClient@ItemBase@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@AEAVCUnSerializeBuffer@2@@Z:
	jmp [rel ItemClient__CreateItemClient]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; KeyCombo

extern KeyCombo__GetTextDescription


; class eqlib::CXStr eqlib::KeyCombo::GetTextDescription(void)const
global ?GetTextDescription@KeyCombo@eqlib@@QEBA?AVCXStr@2@XZ
export ?GetTextDescription@KeyCombo@eqlib@@QEBA?AVCXStr@2@XZ
?GetTextDescription@KeyCombo@eqlib@@QEBA?AVCXStr@2@XZ:
	jmp [rel KeyCombo__GetTextDescription]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; PlayerBase

extern PlayerBase__GetVisibilityLineSegment
extern PcZoneClient__GetItemByID


; public: class eqlib::CLineSegment eqlib::PlayerBase::GetVisibilityLineSegment(class eqlib::PlayerBase const &, unsigned int)
global ?GetVisibilityLineSegment@PlayerBase@eqlib@@QEAA?AVCLineSegment@2@AEBV12@I@Z
export ?GetVisibilityLineSegment@PlayerBase@eqlib@@QEAA?AVCLineSegment@2@AEBV12@I@Z
?GetVisibilityLineSegment@PlayerBase@eqlib@@QEAA?AVCLineSegment@2@AEBV12@I@Z:
	jmp [rel PlayerBase__GetVisibilityLineSegment]


; class eqlib::VePointer<class eqlib::ItemClient> eqlib::PcZoneClient::GetItemByID(int, class eqlib::ItemIndex *, bool) proc near
global ?GetItemByID@PcZoneClient@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@HPEAVItemIndex@2@_N@Z
export ?GetItemByID@PcZoneClient@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@HPEAVItemIndex@2@_N@Z
?GetItemByID@PcZoneClient@eqlib@@QEAA?AV?$VePointer@VItemClient@eqlib@@@2@HPEAVItemIndex@2@_N@Z:
	jmp [rel PcZoneClient__GetItemByID]


;---------------------------------------------------------------------------------------
;---------------------------------------------------------------------------------------
; Misc

extern __CleanItemTags;
extern __STMLToText

; class eqlib::CXStr eqlib::CleanItemTags(class eqlib::CXStr const &, bool) proc near
global ?CleanItemTags@eqlib@@YA?AVCXStr@1@AEBV21@_N@Z
export ?CleanItemTags@eqlib@@YA?AVCXStr@1@AEBV21@_N@Z
?CleanItemTags@eqlib@@YA?AVCXStr@1@AEBV21@_N@Z:
	jmp [rel __CleanItemTags]



; class eqlib::CXStr eqlib::STMLToText(class eqlib::CXStr const &, bool)
global ?STMLToText@eqlib@@YA?AVCXStr@1@AEBV21@_N@Z
export ?STMLToText@eqlib@@YA?AVCXStr@1@AEBV21@_N@Z
?STMLToText@eqlib@@YA?AVCXStr@1@AEBV21@_N@Z:
	jmp [rel __STMLToText]
